#!/usr/bin/env python3
"""Search the playbook notes layer with minimal token output.

Usage:
  lookup.py <words...>                search all projects
  lookup.py -s <slug> <words...>      search one project
  lookup.py --id <ID> [-s <slug>]     print one full entry
  lookup.py --sessions [-s <slug>]    list conversation digests
  lookup.py --tags [-s <slug>]        list all search tags

Reads notes/<slug>/index.json + notes/<slug>/entries/*.md (generated by
scripts/build_notes.py). Exits 0 when results found, 1 when nothing matches.
"""
import glob
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def load_indexes(slug: str | None):
    if slug:
        paths = [os.path.join(ROOT, "notes", slug, "index.json")]
    else:
        paths = sorted(glob.glob(os.path.join(ROOT, "notes", "*", "index.json")))
    out = {}
    for p in paths:
        if not os.path.isfile(p):
            sys.exit(f"no index for slug '{slug}' (run scripts/build_notes.py first)")
        with open(p) as f:
            data = json.load(f)
        out[data["slug"]] = data["entries"]
    return out


def search(entries_by_slug, words):
    q = [w.lower() for w in words if w]
    if not q:
        sys.exit("no search words given; try: lookup.py install testonly")
    hits = []
    for slug, entries in entries_by_slug.items():
        for e in entries:
            hay = " ".join([e["problem"], e["cause"], e["solution"],
                            e["section_title"], " ".join(e["keywords"]),
                            " ".join(e["tags"])]).lower()
            if all(w in hay for w in q):
                kw_hits = sum(1 for w in q if w in " ".join(e["keywords"] + e["tags"]).lower())
                hits.append((kw_hits, slug, e))
    hits.sort(key=lambda h: (-h[0], h[1], h[2]["id"]))
    if not hits:
        print("no matches")
        return 1
    print(f"{len(hits)} match(es):")
    for kw_hits, slug, e in hits[:15]:
        tags = f" [{', '.join(e['tags'])}]" if e["tags"] else ""
        print(f"{e['id']} | {e['problem']}{tags}")
    if len(hits) > 15:
        print(f"... {len(hits) - 15} more; refine your words or use --id <ID>")
    return 0


def show_entry(entries_by_slug, entry_id):
    entry_id = entry_id.upper()
    for slug, entries in entries_by_slug.items():
        for e in entries:
            if e["id"] == entry_id:
                p = os.path.join(ROOT, "notes", slug, "entries", f"{entry_id}.md")
                with open(p) as f:
                    print(f.read().rstrip())
                return 0
    sys.exit(f"no entry '{entry_id}' (ids look like A11, C1, D8…)")


def list_sessions(entries_by_slug):
    for slug in entries_by_slug:
        p = os.path.join(ROOT, "notes", slug, "SESSIONS.md")
        if os.path.isfile(p):
            with open(p) as f:
                print(f.read().rstrip())
    return 0


def list_tags(entries_by_slug):
    tag_map = {}
    for slug, entries in entries_by_slug.items():
        for e in entries:
            for t in e["tags"]:
                tag_map.setdefault(t, []).append(f"{slug}:{e['id']}")
    print(f"{len(tag_map)} tags:")
    for t in sorted(tag_map):
        print(f"{t}: {' '.join(tag_map[t][:8])}")
    return 0


def main():
    args = sys.argv[1:]
    slug = None
    if "-s" in args:
        i = args.index("-s")
        if i + 1 >= len(args):
            sys.exit("-s requires a slug")
        slug = args.pop(i)
        args.pop(i)
    entries = load_indexes(slug)
    if not args:
        sys.exit(__doc__)
    if args[0] == "--id":
        if len(args) != 2:
            sys.exit("usage: lookup.py --id <ID> [-s <slug>]")
        return show_entry(entries, args[1])
    if args[0] == "--sessions":
        return list_sessions(entries)
    if args[0] == "--tags":
        return list_tags(entries)
    return search(entries, args)


if __name__ == "__main__":
    sys.exit(main())
